FROM node AS build

# docker build --build-arg var_firebase=${FIREBASE_TOKEN} ...
# ARG var_firebase
# ENV FIREBASE_TOKEN=$var_firebase
ADD . ${FIREBASE_TOKEN}

RUN mkdir /workspace
WORKDIR /workspace
COPY . /workspace

RUN apt-get update -y
RUN apt-get install -y  openjdk-8-jdk
RUN npm install -g firebase-tools

RUN npm install
RUN firebase emulators:exec  --project 'septapig' 'npm test' --token "${FIREBASE_TOKEN}"
RUN npm run build

